import PageHeader from "@/components/PageHeader";
import { FileTextIcon } from "@/components/icons";

export const metadata = {
  title: "Terms & Conditions",
  description:
    "Read the Ask Madha Terms & Conditions to understand the rules and guidelines for using our app and website.",
};

export default function TermsPage() {
  return (
    <div className="flex flex-col">
      <PageHeader
        title="Terms & Conditions"
        description="Please read these terms carefully before using Ask Madha."
        icon={FileTextIcon}
      />

      <section className="flex-1 bg-background px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl space-y-8 text-muted-foreground">
          <p>
            Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
          </p>

          <div className="space-y-4">
            <h2 className="text-xl font-semibold gradient-text">
              1. Acceptance of terms
            </h2>
            <p>
              By downloading, accessing, or using Ask Madha (the &quot;App&quot;) or our website (the &quot;Site&quot;), you agree to be bound by these Terms & Conditions. If you do not agree with these terms, please do not use the App or Site.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-semibold gradient-text">
              2. Description of service
            </h2>
            <p>
              Ask Madha is a mobile application for Android and iOS that allows users to create an account, log in, and chat with an AI agent about the Bible. The service is provided for personal, non-commercial use unless otherwise agreed.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-semibold gradient-text">
              3. User accounts
            </h2>
            <p>
              To use certain features, you must create an account. You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account. You agree to provide accurate and complete information when creating your account.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-semibold gradient-text">
              4. Acceptable use
            </h2>
            <p>You agree not to use Ask Madha to:</p>
            <ul className="list-disc space-y-2 pl-5">
              <li>Harass, abuse, or harm others.</li>
              <li>Post or share content that is illegal, hateful, violent, or sexually explicit.</li>
              <li>Attempt to reverse engineer, interfere with, or disrupt the App or its services.</li>
              <li>Impersonate another person or misrepresent your affiliation.</li>
              <li>Use automated systems or bots to access the App without authorization.</li>
            </ul>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-semibold gradient-text">
              5. AI-generated content
            </h2>
            <p>
              Responses generated by the AI agent are produced by artificial intelligence and are intended for informational and devotional purposes only. They do not constitute professional religious, legal, medical, or financial advice. Always verify information against the Bible and consult qualified professionals or spiritual leaders as needed.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-semibold gradient-text">
              6. Intellectual property
            </h2>
            <p>
              All content, design, trademarks, and software related to Ask Madha are owned by us or our licensors. You may not copy, modify, distribute, or create derivative works without our prior written permission. User-generated chat content remains your property, but you grant us a limited license to use it to operate and improve the service.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-semibold gradient-text">
              7. Termination
            </h2>
            <p>
              We may suspend or terminate your account at any time if you violate these terms or engage in harmful behavior. You may also delete your account at any time through the app settings.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-semibold gradient-text">
              8. Limitation of liability
            </h2>
            <p>
              To the fullest extent permitted by law, Ask Madha and its creators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the App or Site. Your use of the service is at your own risk.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-semibold gradient-text">
              9. Changes to these terms
            </h2>
            <p>
              We may update these Terms & Conditions from time to time. We will notify you of significant changes by updating the &quot;Last updated&quot; date and, where appropriate, through the App or email.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-semibold gradient-text">
              10. Governing law
            </h2>
            <p>
              These Terms & Conditions shall be governed by and construed in accordance with the laws of the jurisdiction in which Ask Madha operates, without regard to conflict of law principles.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-semibold gradient-text">
              11. Contact us
            </h2>
            <p>
              If you have any questions about these Terms & Conditions, please contact us at{" "}
              <a
                href="mailto:support@askmadha.com"
                className="font-medium text-primary underline-offset-4 hover:underline"
              >
                support@askmadha.com
              </a>
              .
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
